blank_issues_enabled: false
contact_links:
  - name: README
    url: https://github.com/d0mhate/-tg-ws-proxy-Manager-go#readme
    about: Проверьте инструкции по установке и запуску перед созданием issue
